apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: kustomize
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.19.1
    helm:
      valueFiles:
        - $vals/cert-manager/vals.yml
  - repoURL: git@github.com:larenso/cluster_autmation.git
    targetRevision: main
    ref: vals
  - repoURL: git@github.com:larenso/cluster_autmation.git
    targetRevision: main
    path: cert-manager
  project: cluster
  syncPolicy:
    automated: null
    syncOptions:
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
