apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: kustomize
spec:
  destination:
    namespace: cilium
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://helm.cilium.io/
    chart: cilium
    targetRevision: 1.18.2
    helm:
      valueFiles:
        - $vals/cilium/vals.yml
        - $vals/cilium/vals-mon.yml
  - repoURL: git@github.com:larenso/cluster_autmation.git
    targetRevision: main
    ref: vals
  project: cluster
  syncPolicy:
    automated: null
    syncOptions:
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
